### ISSUE TITLE
Is There A Way To Add Start Menu To The Dock?有没有办法将菜单添加到扩展坞?

### ISSUE THREAD

**Issue by MrKillingHunter** [mydockfinder/mydockfinder-for-Win10-Win11#516]
So ive installed mydockfinder and quit nexus and i've noticed that there is no option to add the Windows Start Menu. Is there a way to add it? If not, can you please add this feature

**Comment by mydockfinder** [comment]
添加系统图标 里面有开始菜单




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月2日(星期天) 晚上6:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] Is There A Way To Add Start Menu To The Dock?有没有办法将菜单添加到扩展坞? (Issue #516)






所以我安装了mydockfinder并退出nexus我注意到，没有选择添加Windows开始菜单。有办法加吗？如果没有，可不可以请你添加这个功能

—
直接回复这封邮件，在GitHub上查看或取消订阅.
***@***.***与&gt;.

**Comment by MrKillingHunter** [comment]
> 

抱歉，我不知道该怎么做。有没有教程把 START MENU 添加到 DOCK

**Comment by mydockfinder** [comment]
dock分隔符，右键菜单，添加系统图标，然后右上角选择开始菜单
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月2日(星期天) 晚上8:54
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Is There A Way To Add Start Menu To The Dock?有没有办法将菜单添加到扩展坞? (Issue #516)





   
抱歉，我不知道该怎么做。有没有教程把 START MENU 添加到 DOCK

**Comment by MrKillingHunter** [comment]
我已经完成了您告诉我的步骤，但是当我去添加系统图标时，它没有显示开始菜单选项。我正在使用“MyDock.exe”。是因为我必须使用“Dock.exe”吗？

**Comment by mydockfinder** [comment]
![image](https://user-images.githubusercontent.com/32895737/229354497-1a0f0ea3-de67-4612-8c65-0432aa7c8b7e.png)

**Comment by MrKillingHunter** [comment]
我这边的最后一个选项是“电池”，我找不到“开始菜单”

**Comment by mydockfinder** [comment]
你下载的不会是旧的免费版吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月2日(星期天) 晚上9:04
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Is There A Way To Add Start Menu To The Dock?有没有办法将菜单添加到扩展坞? (Issue #516)





 
我这边的最后一个选项是“电池”，我找不到“开始菜单”
 
&mdash;

**Comment by MrKillingHunter** [comment]
不，我最近刚从 NEXUS 切换后通过 STEAM 下载了它

**Comment by mydockfinder** [comment]
那应该是有的，版本号是1.9.8吗
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月2日(星期天) 晚上9:11
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Is There A Way To Add Start Menu To The Dock?有没有办法将菜单添加到扩展坞? (Issue #516)





 
不，我最近刚从 NEXUS 切换后通过 STEAM 下载了它

**Comment by MrKillingHunter** [comment]
它在 PREFENCES 的 ABOUT 中显示 1.9.8

**Comment by mydockfinder** [comment]
那应该是有的，你的添加系统图标截图我看一下
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月2日(星期天) 晚上9:15
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Is There A Way To Add Start Menu To The Dock?有没有办法将菜单添加到扩展坞? (Issue #516)





 
它在 PREFENCES 的 ABOUT 中显示 1.9.8

**Comment by grafikartes** [comment]
Hello, I just installed it and everything is fine, but the start menu does not open, has anyone had this problem?

**Comment by mydockfinder** [comment]
有没有开始菜单的图标呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月2日(星期天) 晚上11:37
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Is There A Way To Add Start Menu To The Dock?有没有办法将菜单添加到扩展坞? (Issue #516)





 
Hello, I just installed it and everything is fine, but the start menu does not open, has anyone had this problem?
 
&mdash;

**Comment by grafikartes** [comment]
Can you tell me what this is for? it is not the Start Menu ? but when it's in the Dock, we click on it and it doesn't do anything, only with the right click options appear.
<img width="789" alt="Screenshot 2023-04-03 at 09 49 11" src="https://user-images.githubusercontent.com/47481889/229460188-6b22ff32-892f-49f2-a456-eb6a3b563a52.png">

**Comment by mydockfinder** [comment]
这个图标的功能就是点击以后代码模拟按下CTRL+ESC功能，你可以尝试按下键盘的CTRL+ESC能不能显示开始菜单&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月3日(星期一) 下午4:51
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Is There A Way To Add Start Menu To The Dock?有没有办法将菜单添加到扩展坞? (Issue #516)






你能告诉我这是干什么用的吗？它不是开始菜单？但是，当它在码头，我们点击它，它不做任何事情，只有用右键单击选项出现。


—
直接回复这封邮件，在GitHub上查看或取消订阅.
***@***.***与&gt;.

**Comment by MrKillingHunter** [comment]
对不起，我昨天没有回复，已经很晚了，我不得不去睡觉了，但这是你想要的截图

**Comment by mydockfinder** [comment]
这个图标的功能就是点击以后代码模拟按下CTRL+ESC功能，你可以尝试按下键盘的CTRL+ESC能不能显示开始菜单

**Comment by grafikartes** [comment]
I send a video, you can see that it doesn't open, if I do CTRL+ESC on the keyboard it opens without problems, but not on the icon. but I must have something to block here, the other icons all work fine.
https://user-images.githubusercontent.com/47481889/229482557-685acdab-e010-4f8e-bc7a-0a82dfa5226f.mp4

**Comment by mydockfinder** [comment]
偏好设置-高级，里面有屏幕触发角，试一下显示桌面看看能不能正常使用，那个是后台模拟WIN+D，如果也不行就是系统拦截了所有后台模拟键盘按键的功能




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月3日(星期一) 晚上9:02
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Is There A Way To Add Start Menu To The Dock?有没有办法将菜单添加到扩展坞? (Issue #516)





 
Closed #516 as not planned.
 
&mdash;

**Comment by MrKillingHunter** [comment]
I found a alternative to open the start menu by opening it via apple menu bar right click so yea

**Comment by grafikartes** [comment]
It doesn't work, but it's not dramatic, I open it with a keyboard shortcut, the rest is very good!

**Comment by MrKillingHunter** [comment]
maybe its removed in the steam download like idk i aint got any budget

**Comment by mydockfinder** [comment]
但是这两个方法都是同一个代码。。。。




№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月5日(星期三) 下午5:04
***@***.***&gt;;
抄送:&nbsp;"№じ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [mydockfinder/mydockfinder-for-Win10-Win11] Is There A Way To Add Start Menu To The Dock?有没有办法将菜单添加到扩展坞? (Issue #516)





 
I found a alternative to open the start menu by opening it via apple menu bar right click so yea
